# fly.toml app configuration file generated for statstory-backend on 2025-05-03T00:51:58Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'statstory-backend'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1024'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
